site_name: PDSA
site_author: PK
site_description: DESCRIPTION
repo_name: pk1308/PDSA
repo_url: https://github.com/pk1308/PDSA
nav:
- Home:
  - index.md
- week3:
  - week3/list_implementation_3_6.md
  - week3/quick_sort_3_1.md
  - week3/listsinpython3_7.md
  - week3/quicksort_anaylsis_3.2.md
  - week3/list&dictionary_imp_3_9.md
- week5:
  - week5/Lecture 5.6 - Minimum Cost Spanning Trees (Prim_s Algorithm)_annotated.md
  - week5/dijkstra_5_2.md
  - week5/Lecture 5.2 - Single Source Shortest Paths (Dijkstra_s algorithm).md
  - week5/bellman_ford_5_3.md
  - week5/Lecture 5.1 - Shortest Paths in Weighted Graphs_annotated.md
  - week5/Lecture 5.4 - All Pairs Shortest Paths (Floyd-Warshall algorithm)_annotated.md
  - week5/Lecture 5.3 - Single Source Shortest Paths with Negative Weights (Bellman-Ford
    Algorithm)_annotated.md
  - week5/prims.md
  - week5/Lecture 5.5 - Minimum Cost Spanning Trees_annotated.md
  - week5/floyd_warshall_5_4.md
  - week5/kruskal.md
- week1:
  - week1/exception_handling.md
  - week1/class&object.md
  - week1/time_it.md
  - week1/Euclid's Algorithm.md
  - week1/ta_session_06_06.md
- week2:
  - week2/lec2_3.md
  - week2/lec_summary.md
  - week2/week summary.md
  - week2/lec2_2.md
  - week2/insert_sort_2_6.md
  - week2/mergesort2_7.md
  - week2/master theorm.md
  - week2/ppa.md
  - week2/lec2_4_searchinlist.md
  - week2/selection_sort_2_5.md
  - week2/lec2.1.md
  - week2/grpa.md
- week4:
  - week4/pending.md
  - week4/topologoical_sorting.md
  - week4/DFS_4_4.md
  - week4/Lecture 4.3 - Breadth First Search (BFS)_.md
  - week4/BFS_4_3.md
  - week4/Lecture 4.1 - Introduction to graphs_annotated.md
  - week4/longest_path4_8.md
  - week4/redo.md
  - week4/Lecture 4.7 - Topological Sorting.md
  - week4/Lecture 4.5 - Applications of BFS and DFS.md
  - week4/Lecture 4.1 - Introduction to graphs_.md
  - week4/Lecture 4.4 - Depth First Search (DFS)_T.md
  - week4/Lecture 4.3 - Breadth First Search (BFS)_T.md
  - week4/Lecture 4.2 - Representing Graphs_.md
  - week4/represntinggraph4.2.md
  - week4/Lecture 4.8 - Longest Path in DAGs.md
  - week4/Lecture 4.6 - Introduction to Directed Acyclic Graph (DAG).md
  - week4/Lecture 4.4 - Depth First Search (DFS)_.md
- artifacts:
  - artifacts/Algorithms_DASGUPTA.md
- reference:
  - reference/priya_suggestion.md
  - reference/book1.md
  - reference/book2.md
  - reference/book3.md
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.sections
  - toc.integrate
  - navigation.top
  language: en
  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
    primary: teal
    accent: purple
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
    primary: teal
    accent: lime
extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/pk1308
extra_javascript:
- javascripts/config.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
- pymdownx.arithmatex:
    generic: true
- mdx_math
- attr_list
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- admonition
- pymdownx.arithmatex:
    generic: true
- footnotes
- pymdownx.details
- pymdownx.superfences
- pymdownx.mark
- pymdownx.pathconverter
- pymdownx.arithmatex:
    generic: true
extra_css:
- https://unpkg.com/katex@0/dist/katex.min.css
plugins:
- search
- mkdocs-pdf
copyright: '&copy; 2024 <a href="https://github.com/pk1308"  target="_blank" rel="noopener">PK</a>'
